-- This script was generated by the Schema Diff utility in pgAdmin 4. 
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated 
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps. 
BEGIN;
CREATE SEQUENCE public.day_id_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

CREATE SEQUENCE public.general_statistics_minute_id_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

CREATE SEQUENCE public.hour_id_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

CREATE SEQUENCE public.minutedata_id_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

CREATE SEQUENCE public.outlier_id_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

CREATE SEQUENCE public.roles_id_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

CREATE SEQUENCE public.statistics_general_days_id_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

CREATE SEQUENCE public.statistics_general_hours_id_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

CREATE TABLE public.roles
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT roles_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

CREATE TABLE public.statistics_days
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    median real NOT NULL,
    average real NOT NULL,
    "timestamp" timestamp without time zone NOT NULL,
    countrequests bigint NOT NULL,
    percentile95 real NOT NULL,
    percentile99 real NOT NULL,
    endpoint text COLLATE pg_catalog."default" NOT NULL,
    render_time real NOT NULL,
    db_exec_time real NOT NULL,
    CONSTRAINT day_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

CREATE TABLE public.statistics_general_days
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "timestamp" timestamp without time zone NOT NULL,
    downloads integer NOT NULL,
    views bigint NOT NULL,
    private_memory bigint NOT NULL,
    working_set bigint NOT NULL,
    virtual_memory bigint NOT NULL,
    uploads integer NOT NULL,
    uncaught_exceptions integer NOT NULL,
    count_total_requests bigint NOT NULL,
    CONSTRAINT general_statistics_days_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

CREATE TABLE public.statistics_general_hours
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "timestamp" timestamp without time zone NOT NULL,
    downloads integer NOT NULL,
    views bigint NOT NULL,
    private_memory bigint NOT NULL,
    working_set bigint NOT NULL,
    virtual_memory bigint NOT NULL,
    uploads integer NOT NULL,
    uncaught_exceptions integer NOT NULL,
    count_total_requests bigint NOT NULL,
    CONSTRAINT general_statistics_hours_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

CREATE TABLE public.statistics_general_minutes
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "timestamp" timestamp without time zone NOT NULL,
    downloads integer NOT NULL,
    views bigint NOT NULL,
    private_memory bigint NOT NULL,
    working_set bigint NOT NULL,
    virtual_memory bigint NOT NULL,
    uploads integer NOT NULL,
    uncaught_exceptions integer NOT NULL,
    count_total_requests bigint NOT NULL,
    CONSTRAINT general_statistics_minute_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

CREATE TABLE public.statistics_hours
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    median real NOT NULL,
    average real NOT NULL,
    "timestamp" timestamp without time zone NOT NULL,
    countrequests bigint NOT NULL,
    percentile95 real NOT NULL,
    percentile99 real NOT NULL,
    endpoint text COLLATE pg_catalog."default" NOT NULL,
    render_time real NOT NULL,
    db_exec_time real NOT NULL,
    CONSTRAINT hour_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

CREATE TABLE public.statistics_minutes
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    median real NOT NULL,
    average real NOT NULL,
    "timestamp" timestamp without time zone NOT NULL,
    countrequests bigint NOT NULL,
    percentile95 real NOT NULL,
    percentile99 real NOT NULL,
    endpoint text COLLATE pg_catalog."default" NOT NULL,
    render_time real NOT NULL,
    db_exec_time real NOT NULL,
    CONSTRAINT minutedata_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

CREATE TABLE public.statistics_outliers
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "timestamp" timestamp without time zone NOT NULL,
    seconds real NOT NULL,
    reqinfo jsonb NOT NULL,
    endpoint text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT outlier_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

CREATE TABLE public.user_roles
(
    userid integer NOT NULL,
    roleid integer NOT NULL,
    CONSTRAINT user_roles_pkey PRIMARY KEY (userid, roleid),
    CONSTRAINT user_roles_roleid_fkey FOREIGN KEY (roleid)
        REFERENCES public.roles (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT user_roles_userid_fkey FOREIGN KEY (userid)
        REFERENCES public.users (userid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

-- Add default roles
INSERT INTO roles (name)
VALUES ('user'), ('admin');

-- Assign a default role to every user
INSERT INTO user_roles ( userid, roleid )
SELECT userid, 1 FROM users;

END;
